In [25]:
import cv2 as cv
from utils.functions import *
import numpy as np


# 示例用法
video1_path = '../data/testolabc1.avi'
video2_path = '../data/testolabc2.avi'
video3_path = '../data/testolabc3.avi'
video4_path = '../data/testolabc4.avi'
frame_number = 870  # 提取第800帧

# frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
# # 示例用法
# frame1, frame2 = undistort_and_rotate(frame1), undistort_and_rotate(frame2)
# frame1, frame2 = resize_to_equal_width(frame1, frame2)
# kp1, des1 = detect_and_compute_features(frame1, x_range=[0.3, 1.0])
# kp2, des2 = detect_and_compute_features(frame2, x_range=[0.0, 0.7])

# good_matches = match_features(des1, des2)
# H = compute_homography(kp1, kp2, good_matches)

# print(H)
def compute_H1(frame1, frame2, x1_range=[0.4, 1.0], x2_range=[0.0, 0.7]):
    frame1, frame2 = undistort_and_rotate(frame1,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    kp1, des1 = detect_and_compute_features(frame1, x_range=x1_range)
    kp2, des2 = detect_and_compute_features(frame2, x_range=x2_range)

    good_matches = match_features(des1, des2)
    H = compute_homography(kp1, kp2, good_matches)
    return H

def compute_H(frame1, frame2, x1_range=[0.4, 1.0], x2_range=[0.0, 0.7]):
    frame1, frame2 = undistort_and_rotate(frame1,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    kp1, des1 = detect_and_compute_features(frame1, x_range=x1_range)
    kp2, des2 = detect_and_compute_features(frame2, x_range=x2_range)

    good_matches = match_features(des1, des2)
    H = compute_homography(kp1, kp2, good_matches)
    return H
    
frame1, frame2 = read_frames_from_videos(video1_path, video2_path, 0)
frame3, frame4 = read_frames_from_videos(video3_path, video4_path, 970)

H1 = compute_H(frame1, frame2)
H2 = compute_H(frame3, frame4)
print(H1, H2, sep='\n\n')

[[ 1.39781937e+00 -5.56993594e-02  4.62282286e+02]
 [ 1.13962681e-01  1.02690255e+00  5.17578867e+01]
 [ 5.56426020e-04 -1.06309598e-04  1.18287180e+00]]

[[ 9.43926119e-01  6.40145111e-02  3.53352322e+02]
 [-5.38934521e-02  1.06450359e+00 -8.90794874e+00]
 [-1.51448830e-04  7.81687660e-05  9.44239002e-01]]


In [26]:
frame1, frame2 = read_frames_from_videos(video1_path, video2_path, 890)
frame3, frame4 = read_frames_from_videos(video3_path, video4_path, 890)

H1 = compute_H(frame1, frame2)
H2 = compute_H(frame3, frame4)
print(H1, H2, sep='\n\n')

[[ 1.39781937e+00 -5.56993594e-02  4.62282286e+02]
 [ 1.13962681e-01  1.02690255e+00  5.17578867e+01]
 [ 5.56426020e-04 -1.06309598e-04  1.18287180e+00]]

[[ 9.43926119e-01  6.40145111e-02  3.53352322e+02]
 [-5.38934521e-02  1.06450359e+00 -8.90794874e+00]
 [-1.51448830e-04  7.81687660e-05  9.44239002e-01]]


In [24]:
sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
cv.imwrite("stitch1.jpg", sti1)
cv.imwrite("stitch2.jpg", sti2)

H3 = compute_H(sti1, sti2, x1_range=[0.3, 1.0], x2_range=[0.0, 0.4])
result = stitch_images_with_blending(sti1, sti2, H3)
result = crop_black_right(result)
print(H3)
cv.imwrite("result.jpg", result)

[[ 6.84859999e-01 -1.87613581e-02  7.05462964e+02]
 [-6.01093004e-02  7.28536207e-01  3.49847050e+01]
 [-1.18027542e-04 -3.46918610e-05  8.73365943e-01]]


True

In [27]:

import cv2 as cv
import numpy as np
from utils.functions import *


def compute_homographies(video1_path, video2_path, video3_path, video4_path, frame_number1, frame_number2):
    def compute_H(frame1, frame2, x1_range=[0.4, 1.0], x2_range=[0.0, 0.7]):
        frame1, frame2 = undistort_and_rotate(frame1, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32))
        frame1, frame2 = resize_to_equal_width(frame1, frame2)
        kp1, des1 = detect_and_compute_features(frame1, x_range=x1_range)
        kp2, des2 = detect_and_compute_features(frame2, x_range=x2_range)

        good_matches = match_features(des1, des2)
        H = compute_homography(kp1, kp2, good_matches)
        return H

    # 读取帧
    frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number1)
    # frame1 = resize_frame(frame1 , scale=0.98)
    frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number2)

    # 计算单应性矩阵
    H1 = compute_H(frame1, frame2)
    H2 = compute_H(frame3, frame4)

    sti1 = stitch_images_with_blending(frame1, frame2, H1)
    sti2 = stitch_images_with_blending(frame3, frame4, H2)

    H3 = compute_H(sti1, sti2, x1_range=[0.3, 1.0], x2_range=[0.0, 0.4])
    result = stitch_images_with_blending(sti1, sti2, H3)
    cv.imwrite("result.jpg", result)

    return H1, H2, H3

# 示例用法
video1_path = '../data/testolabc1.avi'
video2_path = '../data/testolabc2.avi'
video3_path = '../data/testolabc3.avi'
video4_path = '../data/testolabc4.avi'
frame_number1 = 0
frame_number2 = 890

H1, H2, H3 = compute_homographies(video1_path, video2_path, video3_path, video4_path, frame_number1, frame_number2)
# print(H1, H2, H3, sep='\n\n')

In [28]:
video1_path = '../data/testolabc1.avi'
video2_path = '../data/testolabc2.avi'
video3_path = '../data/testolabc3.avi'
video4_path = '../data/testolabc4.avi'
# frame_number = 830  # 提取第800帧

In [30]:
import cv2
import numpy as np
import os
from multiprocessing import Process, Lock
from time import time

num_processes = 8  # 设置进程数量
frame_times = []
for frame_number in range(900,1200):
    start_time = time()
    frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
    frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)


    frame1, frame2 = undistort_and_rotate(frame1,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    frame3, frame4 = undistort_and_rotate(frame3,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame4, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame3, frame4 = resize_to_equal_width(frame3, frame4)

    sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
    result = stitch_images_with_blending(sti1, sti2, H3)
    result = crop_black_right(result)

    elapsed_time = time() - start_time
    frame_times.append(elapsed_time)

    if len(frame_times) == 5:
        avg_time = sum(frame_times) / len(frame_times)
        frame_times = []  # Reset the list for the next set of frames
    else:
        avg_time = elapsed_time

    frame_rate = num_processes / avg_time if avg_time > 0 else 0
    text = f"FPS: {frame_rate:.2f} Time: {elapsed_time:.2f}"

    cv2.putText(result, text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2)
    cv.imwrite(f'output/result{frame_number}.jpg', result)

In [35]:

import cv2 as cv
import os
import re

def natural_sort_key(s):
    return [int(text) if text.isdigit() else text.lower() for text in re.split('([0-9]+)', s)]

def images_to_video(image_folder, output_video_path, fps=30):
    # 获取所有图片文件名并排序
    images = [img for img in os.listdir(image_folder) if img.endswith((".png", ".jpg", ".jpeg"))]
    images.sort(key=natural_sort_key)
    

    # 读取第一张图片以获取帧的宽度和高度
    frame = cv.imread(os.path.join(image_folder, images[0]))
    height, width, layers = frame.shape

    # 定义视频编写器
    fourcc = cv.VideoWriter_fourcc(*'mp4v')  # 使用mp4v编码
    video = cv.VideoWriter(output_video_path, fourcc, fps, (width, height))

    # 将每张图片写入视频
    for image in images:
        img_path = os.path.join(image_folder, image)
        frame = cv.imread(img_path)
        video.write(frame)

    # 释放视频编写器
    video.release()
    print(f"视频保存到 {output_video_path}")

# 示例用法
image_folder = 'output'
output_video_path = 'output_video.mp4'
images_to_video(image_folder, output_video_path, fps=30)



视频保存到 output_video.mp4


In [36]:
images = [img for img in os.listdir(image_folder) if img.endswith((".png", ".jpg", ".jpeg"))]
images.sort(key=natural_sort_key)
print(images)

['result900.jpg', 'result901.jpg', 'result902.jpg', 'result903.jpg', 'result904.jpg', 'result905.jpg', 'result906.jpg', 'result907.jpg', 'result908.jpg', 'result909.jpg', 'result910.jpg', 'result911.jpg', 'result912.jpg', 'result913.jpg', 'result914.jpg', 'result915.jpg', 'result916.jpg', 'result917.jpg', 'result918.jpg', 'result919.jpg', 'result920.jpg', 'result921.jpg', 'result922.jpg', 'result923.jpg', 'result924.jpg', 'result925.jpg', 'result926.jpg', 'result927.jpg', 'result928.jpg', 'result929.jpg', 'result930.jpg', 'result931.jpg', 'result932.jpg', 'result933.jpg', 'result934.jpg', 'result935.jpg', 'result936.jpg', 'result937.jpg', 'result938.jpg', 'result939.jpg', 'result940.jpg', 'result941.jpg', 'result942.jpg', 'result943.jpg', 'result944.jpg', 'result945.jpg', 'result946.jpg', 'result947.jpg', 'result948.jpg', 'result949.jpg', 'result950.jpg', 'result951.jpg', 'result952.jpg', 'result953.jpg', 'result954.jpg', 'result955.jpg', 'result956.jpg', 'result957.jpg', 'result958.jp

In [3]:

# import concurrent.futures
# import cv2 as cv
# import numpy as np

# def process_frame(frame_number, video1_path, video2_path, video3_path, video4_path, H1, H2, H3):
#     frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
#     frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)

#     frame1, frame2 = undistort_and_rotate(frame1, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32))
#     frame1, frame2 = resize_to_equal_width(frame1, frame2)
#     frame3, frame4 = undistort_and_rotate(frame3, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame4, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32))
#     frame3, frame4 = resize_to_equal_width(frame3, frame4)

#     sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
#     result = stitch_images_with_blending(sti1, sti2, H3)
#     result = crop_black_right(result)

#     output_path = f'output/result{frame_number}.jpg'
#     cv.imwrite(output_path, result)
#     return output_path

# def main():
#     video1_path = '../data/testolabc1.avi'
#     video2_path = '../data/testolabc2.avi'
#     video3_path = '../data/testolabc3.avi'
#     video4_path = '../data/testolabc4.avi'
#     # H1, H2, H3 = np.eye(3), np.eye(3), np.eye(3)  # replace with actual homography matrices

#     with concurrent.futures.ThreadPoolExecutor() as executor:
#         futures = []
#         for frame_number in range(800, 1200):
#             futures.append(executor.submit(process_frame, frame_number, video1_path, video2_path, video3_path, video4_path, H1, H2, H3))
        
#         for future in concurrent.futures.as_completed(futures):
#             print(f'Processed: {future.result()}')

# if __name__ == "__main__":
#     main()

Processed: output/result805.jpg
Processed: output/result800.jpg
Processed: output/result813.jpg
Processed: output/result810.jpg
Processed: output/result803.jpg
Processed: output/result811.jpg
Processed: output/result816.jpg
Processed: output/result809.jpg
Processed: output/result807.jpg
Processed: output/result801.jpg
Processed: output/result804.jpg
Processed: output/result802.jpg
Processed: output/result818.jpg
Processed: output/result819.jpg
Processed: output/result808.jpg
Processed: output/result806.jpg
Processed: output/result812.jpg
Processed: output/result817.jpg
Processed: output/result814.jpg
Processed: output/result815.jpg
Processed: output/result821.jpg
Processed: output/result825.jpg
Processed: output/result820.jpg
Processed: output/result822.jpg
Processed: output/result832.jpg
Processed: output/result829.jpg
Processed: output/result826.jpg
Processed: output/result828.jpg
Processed: output/result831.jpg
Processed: output/result830.jpg
Processed: output/result824.jpg
Processe

In [44]:

import cv2 as cv
import numpy as np
from multiprocessing import Pool

# 假设所有必需的函数和变量都已定义，如 undistort_and_rotate、resize_to_equal_width、stitch_images_with_blending、crop_black_right、read_frames_from_videos

def process_frame(frame_number: int):
    video1_path = '../data/testolabc1.avi'
    video2_path = '../data/testolabc2.avi'
    video3_path = '../data/testolabc3.avi'
    video4_path = '../data/testolabc4.avi'

    dist_coeffs = np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32)
    angle1 = -2.125

    # 读取视频帧
    frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
    frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)

    # 畸变矫正和旋转
    frame1, frame2 = undistort_and_rotate(frame1, dist_coeffs, angle=angle1), undistort_and_rotate(frame2, dist_coeffs)
    frame3, frame4 = undistort_and_rotate(frame3, dist_coeffs, angle=angle1), undistort_and_rotate(frame4, dist_coeffs)

    # 调整大小
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    frame3, frame4 = resize_to_equal_width(frame3, frame4)

    # 图像拼接
    sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
    result = stitch_images_with_blending(sti1, sti2, H3)
    result = crop_black_right(result)

    # 保存结果
    cv.imwrite(f'output/result{frame_number}.jpg', result)

if __name__ == "__main__":
    video1_path = '../data/testolabc1.avi'
    video2_path = '../data/testolabc2.avi'
    video3_path = '../data/testolabc3.avi'
    video4_path = '../data/testolabc4.avi'


    frame_numbers = list(range(1000))

    with Pool(processes=16) as pool:
        pool.map(process_frame, frame_numbers)

In [21]:


# import cv2 as cv
# import numpy as np
# from multiprocessing import Pool
# from typing import Tuple, List

# # 假设所有必需的函数和变量都已定义，如 undistort_and_rotate、resize_to_equal_width、stitch_images_with_blending、crop_black_right、read_frames_from_videos

# def process_frame(frame_number: int) -> Tuple[int, np.ndarray]:
#     video1_path = '../data/testolabc1.avi'
#     video2_path = '../data/testolabc2.avi'
#     video3_path = '../data/testolabc3.avi'
#     video4_path = '../data/testolabc4.avi'

#     dist_coeffs = np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32)
#     angle1 = -2.125

#     # 读取视频帧
#     frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
#     frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)

#     # 畸变矫正和旋转
#     frame1, frame2 = undistort_and_rotate(frame1, dist_coeffs, angle=angle1), undistort_and_rotate(frame2, dist_coeffs)
#     frame3, frame4 = undistort_and_rotate(frame3, dist_coeffs, angle=angle1), undistort_and_rotate(frame4, dist_coeffs)

#     # 调整大小
#     frame1, frame2 = resize_to_equal_width(frame1, frame2)
#     frame3, frame4 = resize_to_equal_width(frame3, frame4)

#     # 图像拼接
#     sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
#     result = stitch_images_with_blending(sti1, sti2, H3)
#     result = crop_black_right(result)

#     # 返回帧号和处理后的结果图像
#     return frame_number, result

# def save_results(results: List[Tuple[int, np.ndarray]]):
#     # 按照帧号排序
#     results.sort(key=lambda x: x[0])
#     for frame_number, result in results:
#         cv.imwrite(f'output/result{frame_number}.jpg', result)

# from time import time

# if __name__ == "__main__":
#     frame_numbers = list(range(128))

#     st = time()
#     with Pool(processes=2) as pool:
#         results = pool.map(process_frame, frame_numbers)

#     save_results(results)
#     print(f"耗时{time()-st:.2f}s")


耗时8.36s


In [45]:

import cv2
import os
import numpy as np

# 设置图片文件夹和输出视频路径
image_folder = 'output'
output_video_path = 'output_video.mp4'

# 获取所有图片文件的名称并排序
images = [img for img in os.listdir(image_folder) if img.endswith(".jpg") or img.endswith(".png")]
images.sort()

# 检查是否有图片
if not images:
    raise ValueError("No images found in the specified folder.")

# 获取图片的尺寸
first_image = cv2.imread(os.path.join(image_folder, images[0]))
height, width, layers = first_image.shape

# 定义视频编写器
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
video = cv2.VideoWriter(output_video_path, fourcc, 30, (width, height))

# 帧平滑算法参数
alpha = 0.8  # 平滑系数，0到1之间，值越大平滑效果越明显

# 初始化前一帧
previous_frame = first_image

# 遍历所有图片
for image_name in images:
    current_frame = cv2.imread(os.path.join(image_folder, image_name))
    
    # 平滑处理
    smoothed_frame = cv2.addWeighted(current_frame, alpha, previous_frame, 1 - alpha, 0)
    
    # 写入视频
    video.write(smoothed_frame)
    
    # 更新前一帧
    previous_frame = smoothed_frame

# 释放视频写入对象
video.release()

print(f"Video saved to {output_video_path}")




Video saved to output_video.mp4
