In [37]:
import cv2 as cv
from utils.functions import *
import numpy as np
# 示例用法
video1_path = '../data/testolabc1.avi'
video2_path = '../data/testolabc2.avi'
video3_path = '../data/testolabc3.avi'
video4_path = '../data/testolabc4.avi'
frame_number = 870  # 提取第800帧

# frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
# # 示例用法
# frame1, frame2 = undistort_and_rotate(frame1), undistort_and_rotate(frame2)
# frame1, frame2 = resize_to_equal_width(frame1, frame2)
# kp1, des1 = detect_and_compute_features(frame1, x_range=[0.3, 1.0])
# kp2, des2 = detect_and_compute_features(frame2, x_range=[0.0, 0.7])

# good_matches = match_features(des1, des2)
# H = compute_homography(kp1, kp2, good_matches)

# print(H)
def compute_H1(frame1, frame2, x1_range=[0.4, 1.0], x2_range=[0.0, 0.7]):
    frame1, frame2 = undistort_and_rotate(frame1,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    kp1, des1 = detect_and_compute_features(frame1, x_range=x1_range)
    kp2, des2 = detect_and_compute_features(frame2, x_range=x2_range)

    good_matches = match_features(des1, des2)
    H = compute_homography(kp1, kp2, good_matches)
    return H

def compute_H(frame1, frame2, x1_range=[0.4, 1.0], x2_range=[0.0, 0.7]):
    frame1, frame2 = undistort_and_rotate(frame1,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    kp1, des1 = detect_and_compute_features(frame1, x_range=x1_range)
    kp2, des2 = detect_and_compute_features(frame2, x_range=x2_range)

    good_matches = match_features(des1, des2)
    H = compute_homography(kp1, kp2, good_matches)
    return H
    
frame1, frame2 = read_frames_from_videos(video1_path, video2_path, 0)
frame3, frame4 = read_frames_from_videos(video3_path, video4_path, 970)

H1 = compute_H(frame1, frame2)
H2 = compute_H(frame3, frame4)
print(H1, H2, sep='\n\n')

[[ 7.34380437e-01  1.32914291e-02  3.68159648e+02]
 [-7.01270956e-02  8.04159496e-01  4.74836964e+01]
 [-1.37426735e-04 -1.94595257e-06  9.31160761e-01]]

[[ 1.11292442e+00  9.56229401e-02  3.42126557e+02]
 [-4.10915023e-02  1.06982322e+00 -6.14246888e+00]
 [-1.17787622e-04  6.64050781e-05  9.64253324e-01]]


In [35]:
frame1, frame2 = read_frames_from_videos(video1_path, video2_path, 800)
frame3, frame4 = read_frames_from_videos(video3_path, video4_path, 970)

H1 = compute_H(frame1, frame2)
H2 = compute_H(frame3, frame4)
print(H1, H2, sep='\n\n')

[[ 9.56951984e-01  4.78738025e-02  3.87001688e+02]
 [-3.25416844e-02  9.08479816e-01  4.57048499e+01]
 [ 2.28728357e-05  3.81013158e-05  1.01164037e+00]]

[[ 1.11292442e+00  9.56229401e-02  3.42126557e+02]
 [-4.10915023e-02  1.06982322e+00 -6.14246888e+00]
 [-1.17787622e-04  6.64050781e-05  9.64253324e-01]]


In [36]:
sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
cv.imwrite("stitch1.jpg", sti1)
cv.imwrite("stitch2.jpg", sti2)

H3 = compute_H(sti1, sti2, x1_range=[0.3, 1.0], x2_range=[0.0, 0.4])
result = stitch_images_with_blending(sti1, sti2, H3)
result = crop_black_right(result)
print(H3)
cv.imwrite("result.jpg", result)

[[ 6.84859999e-01 -1.87613581e-02  7.05462964e+02]
 [-6.01093004e-02  7.28536207e-01  3.49847050e+01]
 [-1.18027542e-04 -3.46918610e-05  8.73365943e-01]]


True

In [5]:
video1_path = '../data/testolabc1.avi'
video2_path = '../data/testolabc2.avi'
video3_path = '../data/testolabc3.avi'
video4_path = '../data/testolabc4.avi'
# frame_number = 830  # 提取第800帧

In [39]:
for frame_number in range(800,1200):

    frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
    frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)


    frame1, frame2 = undistort_and_rotate(frame1,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    frame3, frame4 = undistort_and_rotate(frame3,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame4, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame3, frame4 = resize_to_equal_width(frame3, frame4)

    sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
    result = stitch_images_with_blending(sti1, sti2, H3)
    result = crop_black_right(result)

    cv.imwrite(f'output/result{frame_number}.jpg', result)

In [3]:

# import concurrent.futures
# import cv2 as cv
# import numpy as np

# def process_frame(frame_number, video1_path, video2_path, video3_path, video4_path, H1, H2, H3):
#     frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
#     frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)

#     frame1, frame2 = undistort_and_rotate(frame1, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32))
#     frame1, frame2 = resize_to_equal_width(frame1, frame2)
#     frame3, frame4 = undistort_and_rotate(frame3, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame4, dist_coeffs=np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32))
#     frame3, frame4 = resize_to_equal_width(frame3, frame4)

#     sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
#     result = stitch_images_with_blending(sti1, sti2, H3)
#     result = crop_black_right(result)

#     output_path = f'output/result{frame_number}.jpg'
#     cv.imwrite(output_path, result)
#     return output_path

# def main():
#     video1_path = '../data/testolabc1.avi'
#     video2_path = '../data/testolabc2.avi'
#     video3_path = '../data/testolabc3.avi'
#     video4_path = '../data/testolabc4.avi'
#     # H1, H2, H3 = np.eye(3), np.eye(3), np.eye(3)  # replace with actual homography matrices

#     with concurrent.futures.ThreadPoolExecutor() as executor:
#         futures = []
#         for frame_number in range(800, 1200):
#             futures.append(executor.submit(process_frame, frame_number, video1_path, video2_path, video3_path, video4_path, H1, H2, H3))
        
#         for future in concurrent.futures.as_completed(futures):
#             print(f'Processed: {future.result()}')

# if __name__ == "__main__":
#     main()

Processed: output/result805.jpg
Processed: output/result800.jpg
Processed: output/result813.jpg
Processed: output/result810.jpg
Processed: output/result803.jpg
Processed: output/result811.jpg
Processed: output/result816.jpg
Processed: output/result809.jpg
Processed: output/result807.jpg
Processed: output/result801.jpg
Processed: output/result804.jpg
Processed: output/result802.jpg
Processed: output/result818.jpg
Processed: output/result819.jpg
Processed: output/result808.jpg
Processed: output/result806.jpg
Processed: output/result812.jpg
Processed: output/result817.jpg
Processed: output/result814.jpg
Processed: output/result815.jpg
Processed: output/result821.jpg
Processed: output/result825.jpg
Processed: output/result820.jpg
Processed: output/result822.jpg
Processed: output/result832.jpg
Processed: output/result829.jpg
Processed: output/result826.jpg
Processed: output/result828.jpg
Processed: output/result831.jpg
Processed: output/result830.jpg
Processed: output/result824.jpg
Processe

In [44]:

import cv2 as cv
import numpy as np
from multiprocessing import Pool

# 假设所有必需的函数和变量都已定义，如 undistort_and_rotate、resize_to_equal_width、stitch_images_with_blending、crop_black_right、read_frames_from_videos

def process_frame(frame_number: int):
    video1_path = '../data/testolabc1.avi'
    video2_path = '../data/testolabc2.avi'
    video3_path = '../data/testolabc3.avi'
    video4_path = '../data/testolabc4.avi'

    dist_coeffs = np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32)
    angle1 = -2.125

    # 读取视频帧
    frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
    frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)

    # 畸变矫正和旋转
    frame1, frame2 = undistort_and_rotate(frame1, dist_coeffs, angle=angle1), undistort_and_rotate(frame2, dist_coeffs)
    frame3, frame4 = undistort_and_rotate(frame3, dist_coeffs, angle=angle1), undistort_and_rotate(frame4, dist_coeffs)

    # 调整大小
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    frame3, frame4 = resize_to_equal_width(frame3, frame4)

    # 图像拼接
    sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
    result = stitch_images_with_blending(sti1, sti2, H3)
    result = crop_black_right(result)

    # 保存结果
    cv.imwrite(f'output/result{frame_number}.jpg', result)

if __name__ == "__main__":
    video1_path = '../data/testolabc1.avi'
    video2_path = '../data/testolabc2.avi'
    video3_path = '../data/testolabc3.avi'
    video4_path = '../data/testolabc4.avi'


    frame_numbers = list(range(1000))

    with Pool(processes=16) as pool:
        pool.map(process_frame, frame_numbers)

In [21]:


# import cv2 as cv
# import numpy as np
# from multiprocessing import Pool
# from typing import Tuple, List

# # 假设所有必需的函数和变量都已定义，如 undistort_and_rotate、resize_to_equal_width、stitch_images_with_blending、crop_black_right、read_frames_from_videos

# def process_frame(frame_number: int) -> Tuple[int, np.ndarray]:
#     video1_path = '../data/testolabc1.avi'
#     video2_path = '../data/testolabc2.avi'
#     video3_path = '../data/testolabc3.avi'
#     video4_path = '../data/testolabc4.avi'

#     dist_coeffs = np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32)
#     angle1 = -2.125

#     # 读取视频帧
#     frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
#     frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)

#     # 畸变矫正和旋转
#     frame1, frame2 = undistort_and_rotate(frame1, dist_coeffs, angle=angle1), undistort_and_rotate(frame2, dist_coeffs)
#     frame3, frame4 = undistort_and_rotate(frame3, dist_coeffs, angle=angle1), undistort_and_rotate(frame4, dist_coeffs)

#     # 调整大小
#     frame1, frame2 = resize_to_equal_width(frame1, frame2)
#     frame3, frame4 = resize_to_equal_width(frame3, frame4)

#     # 图像拼接
#     sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
#     result = stitch_images_with_blending(sti1, sti2, H3)
#     result = crop_black_right(result)

#     # 返回帧号和处理后的结果图像
#     return frame_number, result

# def save_results(results: List[Tuple[int, np.ndarray]]):
#     # 按照帧号排序
#     results.sort(key=lambda x: x[0])
#     for frame_number, result in results:
#         cv.imwrite(f'output/result{frame_number}.jpg', result)

# from time import time

# if __name__ == "__main__":
#     frame_numbers = list(range(128))

#     st = time()
#     with Pool(processes=2) as pool:
#         results = pool.map(process_frame, frame_numbers)

#     save_results(results)
#     print(f"耗时{time()-st:.2f}s")


耗时8.36s


In [45]:

import cv2
import os
import numpy as np

# 设置图片文件夹和输出视频路径
image_folder = 'output'
output_video_path = 'output_video.mp4'

# 获取所有图片文件的名称并排序
images = [img for img in os.listdir(image_folder) if img.endswith(".jpg") or img.endswith(".png")]
images.sort()

# 检查是否有图片
if not images:
    raise ValueError("No images found in the specified folder.")

# 获取图片的尺寸
first_image = cv2.imread(os.path.join(image_folder, images[0]))
height, width, layers = first_image.shape

# 定义视频编写器
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
video = cv2.VideoWriter(output_video_path, fourcc, 30, (width, height))

# 帧平滑算法参数
alpha = 0.8  # 平滑系数，0到1之间，值越大平滑效果越明显

# 初始化前一帧
previous_frame = first_image

# 遍历所有图片
for image_name in images:
    current_frame = cv2.imread(os.path.join(image_folder, image_name))
    
    # 平滑处理
    smoothed_frame = cv2.addWeighted(current_frame, alpha, previous_frame, 1 - alpha, 0)
    
    # 写入视频
    video.write(smoothed_frame)
    
    # 更新前一帧
    previous_frame = smoothed_frame

# 释放视频写入对象
video.release()

print(f"Video saved to {output_video_path}")




Video saved to output_video.mp4
