In [2]:
import cv2 as cv
from utils.functions import *
import numpy as np
# 示例用法
video1_path = '../data/testolabc1.avi'
video2_path = '../data/testolabc2.avi'
video3_path = '../data/testolabc3.avi'
video4_path = '../data/testolabc4.avi'
frame_number = 800  # 提取第800帧

# frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
# # 示例用法
# frame1, frame2 = undistort_and_rotate(frame1), undistort_and_rotate(frame2)
# frame1, frame2 = resize_to_equal_width(frame1, frame2)
# kp1, des1 = detect_and_compute_features(frame1, x_range=[0.3, 1.0])
# kp2, des2 = detect_and_compute_features(frame2, x_range=[0.0, 0.7])

# good_matches = match_features(des1, des2)
# H = compute_homography(kp1, kp2, good_matches)

# print(H)
def compute_H1(frame1, frame2, x1_range=[0.4, 1.0], x2_range=[0.0, 0.7]):
    frame1, frame2 = undistort_and_rotate(frame1,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    kp1, des1 = detect_and_compute_features(frame1, x_range=x1_range)
    kp2, des2 = detect_and_compute_features(frame2, x_range=x2_range)

    good_matches = match_features(des1, des2)
    H = compute_homography(kp1, kp2, good_matches)
    return H

def compute_H(frame1, frame2, x1_range=[0.4, 1.0], x2_range=[0.0, 0.7]):
    frame1, frame2 = undistort_and_rotate(frame1,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    kp1, des1 = detect_and_compute_features(frame1, x_range=x1_range)
    kp2, des2 = detect_and_compute_features(frame2, x_range=x2_range)

    good_matches = match_features(des1, des2)
    H = compute_homography(kp1, kp2, good_matches)
    return H
    
frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)

H1 = compute_H(frame1, frame2)
H2 = compute_H(frame3, frame4)
print(H1, H2, sep='\n\n')

[[ 9.56951984e-01  4.78738025e-02  3.87001688e+02]
 [-3.25416844e-02  9.08479816e-01  4.57048499e+01]
 [ 2.28728357e-05  3.81013158e-05  1.01164037e+00]]

[[ 1.10172241e+00  8.15026402e-02  3.33409936e+02]
 [-5.91453241e-02  1.02375955e+00 -2.58047957e+00]
 [-1.66935489e-04  8.02515807e-06  9.49784534e-01]]


In [3]:
sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
cv.imwrite("stitch1.jpg", sti1)
cv.imwrite("stitch2.jpg", sti2)

H3 = compute_H(sti1, sti2, x1_range=[0.3, 1.0], x2_range=[0.0, 0.4])
result = stitch_images_with_blending(sti1, sti2, H3)
result = crop_black_right(result)
print(H3)
cv.imwrite("result.jpg", result)

[[ 7.47198847e-01 -1.62701391e-02  7.21653185e+02]
 [-5.47211163e-02  7.58481028e-01  3.38771528e+01]
 [-1.05993193e-04 -2.10610790e-05  8.94954256e-01]]


True

In [4]:
video1_path = '../data/testolabc1.avi'
video2_path = '../data/testolabc2.avi'
video3_path = '../data/testolabc3.avi'
video4_path = '../data/testolabc4.avi'
frame_number = 800  # 提取第800帧

In [5]:
for frame_number in range(120):

    frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
    frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)


    frame1, frame2 = undistort_and_rotate(frame1,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame2, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    frame3, frame4 = undistort_and_rotate(frame3,dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32), angle=-2.125), undistort_and_rotate(frame4, dist_coeffs=np.array([-0.0733, 0.0833,0,0], dtype=np.float32))
    frame3, frame4 = resize_to_equal_width(frame3, frame4)

    sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
    result = stitch_images_with_blending(sti1, sti2, H3)
    result = crop_black_right(result)

    cv.imwrite(f'output/result{frame_number}.jpg', result)

In [12]:

import cv2 as cv
import numpy as np
from multiprocessing import Pool

# 假设所有必需的函数和变量都已定义，如 undistort_and_rotate、resize_to_equal_width、stitch_images_with_blending、crop_black_right、read_frames_from_videos

def process_frame(frame_number: int):
    video1_path = '../data/testolabc1.avi'
    video2_path = '../data/testolabc2.avi'
    video3_path = '../data/testolabc3.avi'
    video4_path = '../data/testolabc4.avi'

    dist_coeffs = np.array([-0.0733, 0.0833, 0, 0], dtype=np.float32)
    angle1 = -2.125

    # 读取视频帧
    frame1, frame2 = read_frames_from_videos(video1_path, video2_path, frame_number)
    frame3, frame4 = read_frames_from_videos(video3_path, video4_path, frame_number)

    # 畸变矫正和旋转
    frame1, frame2 = undistort_and_rotate(frame1, dist_coeffs, angle=angle1), undistort_and_rotate(frame2, dist_coeffs)
    frame3, frame4 = undistort_and_rotate(frame3, dist_coeffs, angle=angle1), undistort_and_rotate(frame4, dist_coeffs)

    # 调整大小
    frame1, frame2 = resize_to_equal_width(frame1, frame2)
    frame3, frame4 = resize_to_equal_width(frame3, frame4)

    # 图像拼接
    sti1, sti2 = stitch_images_with_blending(frame1, frame2, H1), stitch_images_with_blending(frame3, frame4, H2)
    result = stitch_images_with_blending(sti1, sti2, H3)
    result = crop_black_right(result)

    # 保存结果
    cv.imwrite(f'output/result{frame_number}.jpg', result)

if __name__ == "__main__":
    video1_path = '../data/testolabc1.avi'
    video2_path = '../data/testolabc2.avi'
    video3_path = '../data/testolabc3.avi'
    video4_path = '../data/testolabc4.avi'


    frame_numbers = list(range(128))

    with Pool(processes=8) as pool:
        pool.map(process_frame, frame_numbers)